"""add foreign keys and freshness table

Revision ID: 0e3c18c613c6
Revises: bc04ad0f1825
Create Date: 2026-07-17 16:16:14.542069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e3c18c613c6'
down_revision: Union[str, Sequence[str], None] = 'bc04ad0f1825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_feed_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'arrival_records', 'trips', ['trip_id'], ['trip_id'])
    op.create_foreign_key(None, 'arrival_records', 'routes', ['route_id'], ['route_id'])
    op.create_foreign_key(None, 'arrival_records', 'stops', ['stop_id'], ['stop_id'])
    op.create_foreign_key(None, 'stop_times', 'trips', ['trip_id'], ['trip_id'])
    op.create_foreign_key(None, 'stop_times', 'stops', ['stop_id'], ['stop_id'])
    op.create_foreign_key(None, 'trips', 'routes', ['route_id'], ['route_id'])
    op.create_foreign_key(None, 'trips', 'calendar', ['service_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'stop_times', type_='foreignkey')
    op.drop_constraint(None, 'stop_times', type_='foreignkey')
    op.drop_constraint(None, 'arrival_records', type_='foreignkey')
    op.drop_constraint(None, 'arrival_records', type_='foreignkey')
    op.drop_constraint(None, 'arrival_records', type_='foreignkey')
    op.drop_table('static_feed_meta')
    # ### end Alembic commands ###
