"""drop service_id fk

Revision ID: b689b99db8c4
Revises: 0e3c18c613c6
Create Date: 2026-07-17 16:22:03.997232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b689b99db8c4'
down_revision: Union[str, Sequence[str], None] = '0e3c18c613c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trips_service_id_fkey'), 'trips', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('trips_service_id_fkey'), 'trips', 'calendar', ['service_id'], ['service_id'])
    # ### end Alembic commands ###
